PC Relate (#2054)
* draft

* wip

* wip

* kinda works

* clean up debugs

* sorta works

* kinship estimates are two orders of magnitude too high

* operator overloading!

* a little more cleanup

* minor change

* add R script

* more debugging information

* more implicits and f and k2

* multiply every column pointwise by f

* add k0 stub and k1

* use PC-AiR PCs in test

Practically no change to kinship estimates, changes on the order of
1e-10.

* print counts

* fix print statement

* changes to improve performance

* fix bug when using keytables for export

* some possible performance improvements

* clean up a bit

* wip

* works kind of

* worksish

* adapt to renamed hardCallIterator

* various post-merge fixes

* changes

* fixes

* wip

* fix

* use blockmatrices everywhere, optimize blocksize

* various fixes

* improve require error message

* minor fixes to BetterBlockMatrix

* expose blockSize in `from`

* us indexed row matrix everywhere

* wip

* use bigger value for ksi

* fix bug in toblockmatrixdense

* wip

* more transientness

* formatting

* forgot to commit runPcRelate10PCs.R

* minor fixes & more tests

* wip

* wip

* revert richindexedrowmatrix

* wip

* wip

* last commit for now

* remove environment.yml

* cleanup

* rename maybefast

* remove newline

* undo

* move reference impl

* Revert "undo"

This reverts commit 452b343492c011da75f30baf6c818b7347ed23e6.

If this commit doesn't go in you get errors like:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 33.0 failed 1 times, most recent failure: Lost task 0.0 in stage 33.0 (TID 177, localhost): java.lang.ClassCastException: org.apache.spark.mllib.linalg.distributed.BetterBlockMatrix$IntPartition cannot be cast to org.apache.spark.rdd.CoGroupPartition
	at org.apache.spark.rdd.CoGroupedRDD.compute(CoGroupedRDD.scala:132)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.mllib.linalg.distributed.BetterBlockMatrix$BlockMatrixTransposeRDD.compute(BetterBlockMatrix.scala:154)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.mllib.linalg.distributed.BetterBlockMatrix$BlockMatrixMultiplyRDD.block(BetterBlockMatrix.scala:66)
	at org.apache.spark.mllib.linalg.distributed.BetterBlockMatrix$BlockMatrixMultiplyRDD.leftBlock(BetterBlockMatrix.scala:71)
	at org.apache.spark.mllib.linalg.distributed.BetterBlockMatrix$BlockMatrixMultiplyRDD.compute(BetterBlockMatrix.scala:84)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.CoGroupedRDD$$anonfun$compute$2.apply(CoGroupedRDD.scala:141)
	at org.apache.spark.rdd.CoGroupedRDD$$anonfun$compute$2.apply(CoGroupedRDD.scala:137)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.rdd.CoGroupedRDD.compute(CoGroupedRDD.scala:137)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
	at is.hail.distributedmatrix.BlockMatrixIsDistributedMatrix$.diagonal(BlockMatrixIsDistributedMatrix.scala:77)
	at is.hail.methods.PCRelate$.fTwiddle(PCRelate.scala:232)
	at is.hail.methods.PCRelate$.apply(PCRelate.scala:135)
	at is.hail.methods.PCRelate$.toPairRdd(PCRelate.scala:59)
	at is.hail.methods.PCRelateSuite.runPcRelateHail(PCRelateSuite.scala:43)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcVI$sp$2.apply$mcVI$sp(PCRelateSuite.scala:128)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcVI$sp$2.apply(PCRelateSuite.scala:122)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcVI$sp$2.apply(PCRelateSuite.scala:122)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(PCRelateSuite.scala:122)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1.apply(PCRelateSuite.scala:120)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1$$anonfun$apply$mcVI$sp$1.apply(PCRelateSuite.scala:120)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1.apply$mcVI$sp(PCRelateSuite.scala:120)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1.apply(PCRelateSuite.scala:118)
	at is.hail.methods.PCRelateSuite$$anonfun$baldingNicholsMatchesReference$1.apply(PCRelateSuite.scala:118)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at is.hail.methods.PCRelateSuite.baldingNicholsMatchesReference(PCRelateSuite.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

* blah

* wip

* wip

* matches reference

* remove println

* remove some printlns

* more printlns removed

* fixes

* remove missing annotation

* address comments

* address comments

* extract common code

* fix up test suite

* fix type reference

* use only src/test/resources vcfs in tests

* address type changes

* fix ibs0

* remove capitalization of binomial

* revert changes to IBD

* formatting

* remove unused R file

* add experimental.rst

* fix tests

* fix bug

* fix bug in tests